### ISSUE TITLE
kotlin的协程

### ISSUE THREAD

**Issue by jimium** [allon2/dactor#1]
kotlin从编译器和lib层面实现了协程，你可以在协程基础上分装

**Comment by allon2** [comment]
目前实现协程的方式不少，有kilim，scala,kotlin,spring reactor，kotlin,go等多种方式，协程是这个的基础，后期主要是想实现责任链，父子关系调用等多种复杂关系，将公共部分抽取为单独组件，方便代码的复用。考虑过使用注解方式，不过发现类似这个里面的Step的方式，用注解的方式很难实现，也无法实现代码复用。在高并发、高性能的前提先，尽量降低学习成本，也是这个的目标。kotlin这个没细看过。如果也能实现这个目标更好。其实原来的调度用的是quene模式，后来发现ringbuffer更高效，才换这个的。如何让kotlin兼容spring没仔细研究过。为了实现可视化，在step中还保留了xpoint和ypoint，方便后续可视化界面的开发。
