### ISSUE TITLE
example 怎么启动

### ISSUE THREAD

**Issue by ghost** [allon2/dactor#2]
➜  example git:(master) ✗ gradle bootRun

FAILURE: Build failed with an exception.

* What went wrong:
Task 'bootRun' not found in root project 'example'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s

**Comment by allon2** [comment]
需要在tomcat内启动，没使用jetty启动。
可参考https://blog.csdn.net/langzi7758521/article/details/51612603
在idea中配置tomcat，并启动
